// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlfxnlnaagptismucdpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsZnhubG5hYWdwdGlzbXVjZHBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMzEwMDcsImV4cCI6MjA4NjkwNzAwN30.QUD-ZPValKkMk2L_6T39_ad1ajiZcbvl_kM-p0J55xs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});